export const FETCH_BUSES_REQUEST = 'FETCH_BUSES_REQUEST';
export const FETCH_BUSES_DONE = 'FETCH_BUSES_DONE';

export const DISPLAY_AC_BUSES = 'DISPLAY_AC_BUSES';
export const DISPLAY_NONAC_BUSES = 'DISPLAY_NONAC_BUSES';

export const FETCH_ALL_BUSES = 'FETCH_ALL_BUSES';
export const FETCH_AC_BUSES = 'FETCH_AC_BUSES';
export const FETCH_NONAC_BUSES = 'FETCH_NONAC_BUSES';

export const GET_AC_PREFERENCE = 'GET_AC_PREFERENCE';
export const INVERT_CHECKED = 'INVERT_CHECKED';

export const SET_LIST_ASSISTER = 'SET_LIST_ASSISTER';

export const REFRESH_BUSES_LIST = 'REFRESH_BUSES_LIST';

export const SET_IMAGE = 'SET_IMAGE';

export const SORT_PRICE_HIGH_TO_LOW = "SORT_PRICE_HIGH_TO_LOW";
export const SORT_PRICE_LOW_TO_HIGH = "SORT_PRICE_LOW_TO_HIGH";
export const SORT_RATING_HIGH_TO_LOW = "SORT_RATING_HIGH_TO_LOW";
export const SORT_RATING_LOW_TO_HIGH = "SORT_RATING_LOW_TO_HIGH";

export const SET_SOURCE_NAME = 'SET_SOURCE_NAME';
export const SET_DESTINATION_NAME = 'SET_DESTINATION_NAME';

export const ALTER_PREFERENCE = 'ALTER_PREFERENCE';


export const GET_ERRORS = "GET_ERRORS";
export const SET_NUMBER = 'SET_NUMBER';
export const REGISTER_USER = 'REGISTER_USER';
export const SET_USER = "SET_USER";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_USER = "GET_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const GET_MY_TRIPS = "GET_MY_TRIPS";
export const CLEAR_MY_TRIPS="CLEAR_MY_TRIPS"
export const ADD_PREFERENCES = 'ADD_PREFERENCES';
export const ADD_PREFERENCES_REQUEST = 'ADD_PREFERENCES_REQUEST';
export const ADD_PREFERENCES_SUCCESS = 'ADD_PREFERENCES_SUCCESS';

export const BOOK_BUS = "BOOK_BUS";
export const EMPTY_LISTS = "EMPTY_LISTS";



export const GET_DATE="GET_DATE"

export const SET_USER_DATA="SET_USER_DATA"

export const USER_LOADING="USER_LOADING"